### ISSUE TITLE
command_available? Doesn't work for me

### ISSUE THREAD

**Issue by Lambdanaut** [oscardelben/sheet#12]
The line

>  elsif RUBY_PLATFORM =~ /linux/ && command_available?('xdg-open')

Throws the exception:

> /.gem/ruby/1.9.1/gems/sheet-0.1.5/lib/sheet.rb:78:in ``': No such file or directory - type xdg-open (Errno::ENOENT)

for me if I try to include a url in a cheat sheet. 
BUT If I remove

>  && command_available?('xdg-open')

from the line, it works fine. Does anyone know why that's happening?

**Comment by oscardelben** [comment]
I'll investigate the issue when I'm back home tuesday. Thanks!

**Comment by oscardelben** [comment]
I'm going to return false if command_available throws an exception. Thanks for the heads up.
