### ISSUE TITLE
Error when trying to create sheet

### ISSUE THREAD

**Issue by pertrai1** [oscardelben/sheet#18]
Hi, not sure what is happening here after I install and then go to make a new sheet. Hope you can help. This worked fine on my iMac but my MacBook Pro is giving me troubles:

sheet new st2
/Library/Ruby/Gems/1.8/gems/sheet-0.2.2/bin/../lib/sheet.rb:22:in `exec': No such file or directory - /usr/local/bin/mate -w /Users/robsimpson/.sheets/st2 (Errno::ENOENT)
    from /Library/Ruby/Gems/1.8/gems/sheet-0.2.2/bin/../lib/sheet.rb:22:in`exec'
    from /Library/Ruby/Gems/1.8/gems/sheet-0.2.2/lib/sheet/write.rb:13:in `write'
    from /Library/Ruby/Gems/1.8/gems/sheet-0.2.2/bin/../lib/sheet.rb:121:in`write'
    from /Library/Ruby/Gems/1.8/gems/sheet-0.2.2/bin/../lib/sheet.rb:105:in `process'
    from /Library/Ruby/Gems/1.8/gems/sheet-0.2.2/bin/sheet:5
    from /usr/bin/sheet:19:in`load'
    from /usr/bin/sheet:19

**Comment by oscardelben** [comment]
Hi, You can use `/usr/local/bin/mate -w` with other files right?

**Comment by pertrai1** [comment]
Hi, yes I can use mate with other files. So I put mate into the /usr/local/bin as it was in ~/bin but now I get:

Can't find TextMate.app (error -10814)
Abort trap: 6

**Comment by oscardelben** [comment]
There is an option from the textmate menu to add the binary. I think you should be using that one.
