### ISSUE TITLE
Copy command should not print output on success

### ISSUE THREAD

**Issue by noahfrederick** [oscardelben/sheet#6]
In the spirit of Unix utilities, I think it would be more elegant if `sheet copy <name>` did _not_ produce output (such as "Copied!") on success. I always do a double take thinking there was an error.

Thanks for your consideration,
—N

**Comment by oscardelben** [comment]
Fixed, thanks (pushing a new gem update as well).

**Comment by noahfrederick** [comment]
:thumbsup:
