### ISSUE TITLE
Please set the $EDITOR variable to write files

### ISSUE THREAD

**Issue by DeviaVir** [oscardelben/sheet#7]
After "sheet new name", I receive this message. What should I do?

**Comment by thelfensdrfer** [comment]
export EDITOR=xyz 

where xyz is your favorite text editor like "vim", "vi" or "nano"

**Comment by Lambdanaut** [comment]
If you'd like to run that command every time your machine boots up, put "export EDITOR=xyz" in your /etc/rc.local file.

**Comment by funollet** [comment]
Taken from the bash man pages:

```
Bash  attempts  to  invoke  $VISUAL, $EDITOR, and emacs as the editor, in that order.
```

Many people have just VISUAL defined in its environment. Checking both variables would make sheet "just work" for more users.

**Comment by oscardelben** [comment]
I didn't know about $VISUAL, I'll add that check, thanks.

**Comment by oscardelben** [comment]
Done.
