### ISSUE TITLE
Minor UX improvement: friendlier message when sheet list is empty

### ISSUE THREAD

**Issue by igrigorik** [oscardelben/sheet#8]
``` bash
igrigorik { ~ } > gem install sheet
Fetching: sheet-0.1.5.gem (100%)
Successfully installed sheet-0.1.5
1 gem installed
igrigorik { ~ } > sheet list
ls: /Users/igrigorik/.sheets: No such file or directory
```

That interaction immediately makes me think that the tool broke.. After I added a sheet, it works fine though. Probably warrants a friendlier message for those getting started. :)

**Comment by oscardelben** [comment]
I'll do that, thanks. I'm out of town till tuesday though.

**Comment by oscardelben** [comment]
Done thanks. Will be out in the next version
